# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4593177a36bd5bbad968be5ff5406780a630a913422bfd2bbf9b6a4d52cb0c0118d4e9e7fc9bacfa340a40bcf487705668b16e5849a4c63e1850fe33f0196d50

test:
  secret_key_base: a78d93d1a2b91316d1386920adce9e45cd966bb6282cc8a794e935d2cfedb106379db65332f9c714946f3083c1722978a0b2ace95cdd6dcac98d856294ec4b4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
